### ISSUE TITLE
Exporting the checkpoint as a pb file

### ISSUE THREAD

**Issue by harshithdwivedi** [YeongHyeon/R-CNN_LIGHT#2]
How do we export the trained checkpoint as a pb file and use it with tensorflow?
It would be helpful if you could add a working example of doing so, thanks!

**Comment by YeongHyeon** [comment]
Hi,
I am sorry for the late confirmation.
If you are still finding the above, the below link will be helpful.

https://github.com/tensorflow/tensorflow/issues/42818

Thank you for your interest.
Have a nice end of the year.
